### ISSUE TITLE
ConvPDF does not have free parameters

### ISSUE THREAD

**Issue by marinang** [zfit/zfit-physics#4]
I wanted to try a new model convoluted with a gaussian 

``` pyhton
    dcb = GaussLExpRTail(obs=obs, mu=mu, sigma=sigma, kl=kl, alphar=alphar, nr=nr)
    
    conv = zfit.pdf.Gauss(mu=mu, sigma=sigmac, obs=obs)
    pdf = zphys.unstable.pdf.ConvPDF(func=lambda x: dcb.pdf(x),
                                     kernel=lambda x: conv.pdf(x),
                                     limits=obs, obs=obs)
```

however after creating the loss and trying to minimise it I get the following message 

```
<ipython-input-31-9a7d6d870883> in fit(tau)
     15     nll = UnbinnedNLL(model=[model], data=[data_], fit_range=[obs])
     16 
---> 17     minimum = minimizer.minimize(loss=nll)
     18     #append_fit(minimum, mass, tau)
     19 

~/anaconda3/envs/tfn/lib/python3.7/site-packages/zfit-0.3.3-py3.7.egg/zfit/minimizers/baseminimizer.py in minimize(self, loss, params)
    201             `FitResult`: The fit result.
    202         """
--> 203         params = self._check_input_params(loss=loss, params=params, only_floating=True)
    204         with ExitStack() as stack:
    205             tuple(stack.enter_context(param.set_sess(self.sess)) for param in params)

~/anaconda3/envs/tfn/lib/python3.7/site-packages/zfit-0.3.3-py3.7.egg/zfit/minimizers/baseminimizer.py in _check_input_params(self, loss, params, only_floating)
    101             params = list(params)
    102         if not params:
--> 103             raise RuntimeError("No parameter for minimization given/found. Cannot minimize.")
    104         return params
    105 

RuntimeError: No parameter for minimization given/found. Cannot minimize.
```

**Comment by mayou36** [comment]
I see why this happens, it should actually be a Functor. It cannot auto-infer parameters.

What should work is if you give _explicitly_ the parameters to minimize to the minimizer. Can you confirm that this works?

And I'll change it so that is takes pdfs, which is the proper way to go. Then it can also automatically infer the parameters

**Comment by mayou36** [comment]
I've pushed the new pdf, it takes now pdfs only.

You may be interested in the change: https://github.com/zfit/zfit-physics/commit/83b082e3a5c915d5f30c2db3786365ec854ba8b8#diff-085535079b9e384e4725d7e9d19075d0L32

It is now (correctly) a Functor. A PDF that depends on other pdfs. And in the link given, the pdfs are given to the super init. super knows how to handle params etc. This way all the dependencies are automatically managed correctly.

**Comment by jonas-eschle** [comment]
just a test. @all-contributors, please add @jonas-eschle to code
